//@ui5-bundle sample-app/Component-preload.js
sap.ui.predefine("sample-app/Component", ["sap/ui/core/UIComponent","sap/ui/model/json/JSONModel","sample-app/controller/HelloDialog"],function(e,n,o){"use strict";return e.extend("sample-app.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);const t={recipient:{name:"World"}};const i=new n(t);this.setModel(i);this.helloDialog=new o}})});
sap.ui.predefine("sample-app/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("sample-app.controller.App",{onOpenDialog:function(){this.getOwnerComponent().helloDialog.open(this.getView())}})});
sap.ui.predefine("sample-app/controller/HelloDialog", ["sap/ui/base/Object"],function(e){"use strict";return e.extend("sample-app.controller.HelloDialog",{_getDialog:function(){if(!this._oDialog){this._oDialog=sap.ui.xmlfragment("sample-app.view.HelloDialog",this)}return this._oDialog},open:function(e){const i=this._getDialog();e.addDependent(i);i.open()},onCloseDialog:function(){this._getDialog().close()}})});
sap.ui.predefine("sample-app/controller/HelloPanel.controller", ["sap/ui/core/mvc/Controller","sap/m/MessageToast"],function(e,t){"use strict";return e.extend("sample-app.controller.HelloPanel",{onShowHello:function(){const e=this.getOwnerComponent().getModel("i18n").getResourceBundle();e.then(e=>{const o=this.getView().getModel().getProperty("/recipient/name");const n=e.getText("helloMsg",[o]);t.show(n)})},onOpenDialog:function(){this.getOwnerComponent().helloDialog.open(this.getView())}})});
sap.ui.predefine("sample-app/controller/InvoiceList.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sample-app/model/formatter","sap/ui/model/Filter","sap/ui/model/FilterOperator"],function(e,t,i,n,o){"use strict";return e.extend("sample-app.controller.InvoiceList",{formatter:i,onInit:function(){const e=new t({currency:"EUR"});this.getView().setModel(e,"view")},onFilterInvoices:function(e){const t=[];const i=e.getParameter("query");if(i){t.push(new n("ProductName",o.Contains,i))}const r=this.getView().byId("invoiceList");const s=r.getBinding("items");s.filter(t)}})});
sap.ui.predefine("sample-app/model/formatter", ["sap/ui/core/Component"],function(t){"use strict";return{statusText:function(e){const n=t.getOwnerComponentFor(this);if(!n){return e}const u=n.getModel("i18n").getResourceBundle();switch(e){case"A":return u.getText("invoiceStatusA");case"B":return u.getText("invoiceStatusB");case"C":return u.getText("invoiceStatusC");default:return e}}}});
sap.ui.predefine("sample-app/util/Helper", ["require"],e=>{"use strict";return{resolvePath(r){return e.toUrl("../")+r}}});
sap.ui.require.preload({
	"sample-app/i18n/i18n.properties":'TITLE=todos\nINPUT_PLACEHOLDER=What needs to be done?\nCLEAR_COMPLETED=Clear completed\nACTIVE_ITEMS=Active items\nACTIVE_ITEMS_CONTAINING=Active items containing "{0}"\nCOMPLETED_ITEMS=Completed items\nCOMPLETED_ITEMS_CONTAINING=Completed items containing "{0}"\nITEMS_CONTAINING=Items containing "{0}"\nLABEL_ALL=All\nLABEL_ACTIVE=Active\nLABEL_COMPLETED=Completed\n# Hello Panel\nshowHelloButtonText=Say Hello\nhelloMsg=Hello {0}\n# App Descriptor\nappTitle=Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\nhomePageTitle=Walkthrough\nhelloPanelTitle=Hello World\n\nopenDialogButtonText=Say Hello With Dialog\ndialogCloseButtonText=Ok \ninvoiceListTitle=Invoices\ninvoiceStatusA=New\ninvoiceStatusB=In Progress\ninvoiceStatusC=Done',
	"sample-app/i18n/i18n_de.properties":'TITLE=Todos\nINPUT_PLACEHOLDER=Was muss getan werden?\nCLEAR_COMPLETED=Erledigte Eintr\\u00e4ge entfernen\nACTIVE_ITEMS=Aktive Eintr\\u00e4ge\nACTIVE_ITEMS_CONTAINING=Aktive Eintr\\u00e4ge mit "{0}"\nCOMPLETED_ITEMS=Erledigte Eintr\\u00e4ge\nCOMPLETED_ITEMS_CONTAINING=Erledigte Eintr\\u00e4ge mit "{0}"\nITEMS_CONTAINING=Eintr\\u00e4ge mit "{0}"\nLABEL_ALL=Alle\nLABEL_ACTIVE=Aktiv\nLABEL_COMPLETED=Erledigt\n# Hello Panel\nshowHelloButtonText=Say Hello\nhelloMsg=Hello {0}\n# App Descriptor\nappTitle=Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\n',
	"sample-app/i18n/i18n_en.properties":'TITLE=todos\nINPUT_PLACEHOLDER=What needs to be done?\nCLEAR_COMPLETED=Clear completed\nACTIVE_ITEMS=Active items\nACTIVE_ITEMS_CONTAINING=Active items containing "{0}"\nCOMPLETED_ITEMS=Completed items\nCOMPLETED_ITEMS_CONTAINING=Completed items containing "{0}"\nITEMS_CONTAINING=Items containing "{0}"\nLABEL_ALL=All\nLABEL_ACTIVE=Active\nLABEL_COMPLETED=Completed\n# Hello Panel\nshowHelloButtonText=Say Hello\nhelloMsg=Hello {0}\n# App Descriptor\nappTitle=Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\n',
	"sample-app/manifest.json":'{"_version":"1.61.0","sap.app":{"id":"sample-app","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":["","de","en"]},"title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"_version":"1.1.0","technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true},"supportedThemes":["sap_bluecrystal"]},"sap.ui5":{"dependencies":{"minUI5Version":"1.121.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.f":{}}},"rootView":{"viewName":"sample-app.view.App","type":"XML","id":"app"},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sample-app.i18n.i18n","async":true,"supportedLocales":["","de","en"]}},"invoice":{"type":"sap.ui.model.json.JSONModel","uri":"Invoices.json"}},"resources":{"css":[{"uri":"css/styles.css"}]}}}',
	"sample-app/view/App.view.xml":'<mvc:View\n    controllerName="sample-app.controller.App"\n    xmlns="sap.m"\n    xmlns:mvc="sap.ui.core.mvc"\n    displayBlock="true"\n><App class="myAppDemoWT"><pages><Page title="{i18n>homePageTitle}"><headerContent><Button\n                        icon="sap-icon://hello-world"\n                        press="onOpenDialog"\n                    /></headerContent><content><mvc:XMLView viewName="sample-app.view.HelloPanel" /><mvc:XMLView  viewName="sample-app.view.InvoiceList"/></content></Page></pages></App></mvc:View>\n',
	"sample-app/view/HelloDialog.fragment.xml":'<core:FragmentDefinition\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n><Dialog title="Hello {/recipient/name}"><content><core:Icon src="sap-icon://hello-world"\n                    size="8rem"\n                    class="sapUiMediumMargin"/></content><beginButton><Button text="{i18n>dialogCloseButtonText}"\n                    press="onCloseDialog" /></beginButton></Dialog></core:FragmentDefinition>\n',
	"sample-app/view/HelloPanel.view.xml":'<mvc:View\n   controllerName="sample-app.controller.HelloPanel"\n   xmlns="sap.m"\n   xmlns:mvc="sap.ui.core.mvc"><Panel\n      headerText="{i18n>helloPanelTitle}"\n      class="sapUiResponsiveMargin"\n      width="auto" ><content><Button\n         icon="sap-icon://world"\n         text="{i18n>openDialogButtonText}"\n         press="onOpenDialog"\n         class="sapUiSmallMarginEnd"/><Button\n            text="{i18n>showHelloButtonText}"\n            press="onShowHello"\n            class="sapUiDemoWTmyCustomButton"/><Input\n            value="{/recipient/name}"\n            valueLiveUpdate="true"\n            width="60%"/><Text\n            text="Hello {/recipient/name}"\n            class="sapUiSmallMargin sapThemeHighlight-asColor myCustomText"/></content></Panel></mvc:View>',
	"sample-app/view/InvoiceList.view.xml":'<mvc:View\n\tcontrollerName="sample-app.controller.InvoiceList"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><List\n\t\tid="invoiceList"\n\t\theaderText="{i18n>invoiceListTitle}"\n\t\tclass="sapUiResponsiveMargin"\n\t\twidth="auto"\n\t\titems="{\n\t\t\t\t\tpath: \'invoice>/Invoices\' ,\n\t\t\t\t\tsorter : { path: \'ShipperName\',\n\t\t\t\t\t\t\t   group : true } \n\t\t\t\t}"><headerToolbar><Toolbar><Title text="{i18n>invoiceListTitle}"/><ToolbarSpacer/><SearchField width="50%" search="onFilterInvoices" selectOnFocus="false"/></Toolbar></headerToolbar><items><ObjectListItem\n\t\t\t\ttitle="{invoice>Quantity} x {invoice>ProductName}"\n\t\t\t\tnumber="{\n\t\t\t\t\tparts: [{path: \'invoice>ExtendedPrice\'}, {path: \'view>/currency\'}],\n\t\t\t\t\ttype: \'sap.ui.model.type.Currency\',\n\t\t\t\t\tformatOptions: {\n\t\t\t\t\t\tshowMeasure: false\n\t\t\t\t\t}\n\t\t\t\t}"\n\t\t\t\tnumberUnit="{view>/currency}"\n\t\t\t\tnumberState="{=\t${invoice>ExtendedPrice} > 50 ? \'Error\' : \'Success\' }"><firstStatus><ObjectStatus text="{\n\t\t\t\t\t\tpath: \'invoice>Status\',\n\t\t\t\t\t\tformatter: \'.formatter.statusText\'\n\t\t\t\t\t}"/></firstStatus></ObjectListItem></items></List></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
