//@ui5-bundle sample-app/Component-preload.js
sap.ui.predefine("sample-app/Component", ["sap/ui/core/UIComponent","sap/ui/model/json/JSONModel","sample-app/controller/HelloDialog"],(e,o,t)=>{"use strict";return e.extend("sample-app.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);const n={recipient:{name:"World"}};const i=new o(n);this.setModel(i);this.HelloDialog=new t}})});
sap.ui.predefine("sample-app/controller/App.controller", ["sap/ui/Device","sap/ui/core/mvc/Controller","sap/ui/model/Filter","sap/ui/model/FilterOperator","sap/ui/model/json/JSONModel","sap/base/strings/formatMessage","sap/m/MessageToast"],(e,s,a,p,r,o,i)=>{"use strict";return s.extend("sample-app.controller.App",{})});
sap.ui.predefine("sample-app/controller/HelloDialog", ["sap/ui/base/Object"],function(e){"use strict";return e.extend("sample-app.controller.HelloDialog",{_getDialog:function(){if(!this._oDialog){this._oDialog=sap.ui.xmlfragment("sample-app.view.HelloDialog",this)}return this._oDialog},open:function(e){const i=this._getDialog();e.addDependent(i);i.open()},onCloseDialog:function(){this._getDialog().close()}})});
sap.ui.predefine("sample-app/controller/HelloPanel.controller", ["sap/ui/core/mvc/Controller","sap/m/MessageToast"],function(e,o){"use strict";return e.extend("sample-app.controller.HelloPanel",{onShowHello:function(){const e=this.getOwnerComponent().getModel("i18n").getResourceBundle();e.then(e=>{const t=this.getView().getModel().getProperty("/recipient/name");const i=e.getText("helloMsg",[t]);o.show(i)});console.log(e)},_getDialog:function(){if(!this._oDialog){this._oDialog=sap.ui.xmlfragment("sample-app.view.HelloDialog",this);this.getView().addDependent(this._oDialog)}return this._oDialog},onOpenDialog:function(){this._getDialog().open()},onCloseDialog:function(){this._getDialog().close()}})});
sap.ui.predefine("sample-app/util/Helper", ["require"],e=>{"use strict";return{resolvePath(r){return e.toUrl("../")+r}}});
sap.ui.require.preload({
	"sample-app/i18n/i18n.properties":'TITLE=todos\nINPUT_PLACEHOLDER=What needs to be done?\nCLEAR_COMPLETED=Clear completed\nACTIVE_ITEMS=Active items\nACTIVE_ITEMS_CONTAINING=Active items containing "{0}"\nCOMPLETED_ITEMS=Completed items\nCOMPLETED_ITEMS_CONTAINING=Completed items containing "{0}"\nITEMS_CONTAINING=Items containing "{0}"\nLABEL_ALL=All\nLABEL_ACTIVE=Active\nLABEL_COMPLETED=Completed\n# Hello Panel\nshowHelloButtonText=Say Hello\nhelloMsg=Hello {0}\n# App Descriptor\nappTitle=Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\nhomePageTitle=Walkthrough\nhelloPanelTitle=Hello World\n\nopenDialogButtonText=Say Hello With Dialog\ndialogCloseButtonText=Ok ',
	"sample-app/i18n/i18n_de.properties":'TITLE=Todos\nINPUT_PLACEHOLDER=Was muss getan werden?\nCLEAR_COMPLETED=Erledigte Eintr\\u00e4ge entfernen\nACTIVE_ITEMS=Aktive Eintr\\u00e4ge\nACTIVE_ITEMS_CONTAINING=Aktive Eintr\\u00e4ge mit "{0}"\nCOMPLETED_ITEMS=Erledigte Eintr\\u00e4ge\nCOMPLETED_ITEMS_CONTAINING=Erledigte Eintr\\u00e4ge mit "{0}"\nITEMS_CONTAINING=Eintr\\u00e4ge mit "{0}"\nLABEL_ALL=Alle\nLABEL_ACTIVE=Aktiv\nLABEL_COMPLETED=Erledigt\n# Hello Panel\nshowHelloButtonText=Say Hello\nhelloMsg=Hello {0}\n# App Descriptor\nappTitle=Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\n',
	"sample-app/i18n/i18n_en.properties":'TITLE=todos\nINPUT_PLACEHOLDER=What needs to be done?\nCLEAR_COMPLETED=Clear completed\nACTIVE_ITEMS=Active items\nACTIVE_ITEMS_CONTAINING=Active items containing "{0}"\nCOMPLETED_ITEMS=Completed items\nCOMPLETED_ITEMS_CONTAINING=Completed items containing "{0}"\nITEMS_CONTAINING=Items containing "{0}"\nLABEL_ALL=All\nLABEL_ACTIVE=Active\nLABEL_COMPLETED=Completed\n# Hello Panel\nshowHelloButtonText=Say Hello\nhelloMsg=Hello {0}\n# App Descriptor\nappTitle=Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\n',
	"sample-app/manifest.json":'{"_version":"1.61.0","sap.app":{"id":"sample-app","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":["","de","en"]},"title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"_version":"1.1.0","technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true},"supportedThemes":["sap_bluecrystal"]},"sap.ui5":{"dependencies":{"minUI5Version":"1.121.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.f":{}}},"rootView":{"viewName":"sample-app.view.App","type":"XML","id":"app"},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sample-app.i18n.i18n","async":true,"supportedLocales":["","de","en"]}}},"resources":{"css":[{"uri":"css/styles.css"}]}}}',
	"sample-app/view/App.view.xml":'<mvc:View\n   controllerName="sample-app.controller.App"\n   xmlns="sap.m"\n   xmlns:mvc="sap.ui.core.mvc"\n   displayBlock="true" ><App class="sapUiDemoWT"><pages><Page title="{i18n>homePageTitle}"><content><mvc:XMLView viewName="sample-app.view.HelloPanel"/></content></Page></pages></App></mvc:View>',
	"sample-app/view/HelloDialog.fragment.xml":'<core:FragmentDefinition\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n><Dialog title="Hello {/recipient/name}"><content><core:Icon src="sap-icon://hello-world"\n                    size="8rem"\n                    class="sapUiMediumMargin"/></content><beginButton><Button text="{i18n>dialogCloseButtonText}"\n                    press="onCloseDialog" /></beginButton></Dialog></core:FragmentDefinition>\n',
	"sample-app/view/HelloPanel.view.xml":'<mvc:View\n   controllerName="sample-app.controller.HelloPanel"\n   xmlns="sap.m"\n   xmlns:mvc="sap.ui.core.mvc"><Panel\n      headerText="{i18n>helloPanelTitle}"\n      class="sapUiResponsiveMargin"\n      width="auto" ><content><Button\n         icon="sap-icon://world"\n         text="{i18n>openDialogButtonText}"\n         press="onOpenDialog"\n         class="sapUiSmallMarginEnd"/><Button\n            text="{i18n>showHelloButtonText}"\n            press="onShowHello"\n            class="sapUiDemoWTmyCustomButton"/><Input\n            value="{/recipient/name}"\n            valueLiveUpdate="true"\n            width="60%"/><Text\n            text="Hello {/recipient/name}"\n            class="sapUiSmallMargin sapThemeHighlight-asColor myCustomText"/></content></Panel></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
